version: "3.7"

services:
  www:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: "${DOCKER_APP_NAME}_www"
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - .docker/wp-content:/var/www/html/wp-content:delegated
      - ".:/var/www/html/wp-content/plugins/${DOCKER_APP_NAME}:delegated"
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - network

  wordpress:
    container_name: "${DOCKER_APP_NAME}_wordpress"
    build:
      context: .
      dockerfile: .docker/Dockerfile.wordpress
    links:
      - db
    env_file: 
      - .docker/wordpress.env
    volumes:
      - .docker/.bashrc:/root/.bashrc:cached
      - .docker/share:/root/share:delegated
      - wordpress:/var/www/html
      - .docker/wp-content:/var/www/html/wp-content:delegated
      - ".:/var/www/html/wp-content/plugins/${DOCKER_APP_NAME}:delegated"
      - type: tmpfs
        target: "/var/www/html/wp-content/plugins/${DOCKER_APP_NAME}/.docker/share"
        volume:
          nocopy: true
        tmpfs:
          size: 0
      - type: tmpfs
        target: "/var/www/html/wp-content/plugins/${DOCKER_APP_NAME}/.docker/wp-content"
        volume:
          nocopy: true
        tmpfs:
          size: 0
    networks:
      - network

  db:
    container_name: "${DOCKER_APP_NAME}_db"
    build:
      context: .
      dockerfile: .docker/Dockerfile.db
    env_file: 
        - .docker/db.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - network
    ports:
      - 3306

volumes:
  db:
  wordpress:
  node_modules:
  
networks:
  network:
    name: "${DOCKER_APP_NAME}_network"
    driver: bridge 